"use client";

import {
  Brain,
  Cpu,
  LineChart,
  Mic2,
  Terminal,
  MonitorSmartphone,
  Coins,
  PenTool,
  Code2,
  BarChart3,
  Layers,
  ShieldAlert,
  Globe,
  Zap,
} from "lucide-react";
import { PlatformCourse } from "./types";

export const PLATFORM_COURSES: PlatformCourse[] = [
  {
    id: "llm-architecture",
    slug: "llm-architecture",
    title: "Large Language Model Architecture",
    category: "ai",
    level: "Advanced",
    students: "1.2k",
    status: "Operational",
    description:
      "Deep dive into transformer logic with a practical neural sandbox.",
    longDescription:
      "This course teaches how modern language models are built, trained, optimized, and deployed. You’ll move from attention mechanisms to practical inference pipelines and real-world model tuning.",
    instructor: "Dr. Elias Mwangi",
    duration: "8 weeks",
    progress: 64,
    xpReward: 500,
    rating: 4.9,
    gradient: "from-blue-600/20 to-indigo-600/20",
    border: "border-blue-500/30",
    color: "text-blue-400",
    icon: <Brain size={18} />,
    toolIcon: <Cpu size={16} className="text-blue-400" />,
    tools: ["Neural Sandbox", "Weight Visualizer", "Prompt Lab"],
    outcomes: [
      "Understand transformers and attention",
      "Build prompt workflows and evaluation systems",
      "Learn fine-tuning and deployment patterns",
    ],
    modules: [
      {
        id: "m1",
        title: "Transformer Foundations",
        summary: "Attention, tokens, embeddings, context windows.",
        duration: "1h 42m",
        lessons: 8,
      },
      {
        id: "m2",
        title: "Inference & Prompting",
        summary: "Prompt engineering, RAG, output control.",
        duration: "2h 10m",
        lessons: 10,
      },
      {
        id: "m3",
        title: "Optimization & Fine-Tuning",
        summary: "Model adaptation and evaluation workflows.",
        duration: "1h 58m",
        lessons: 7,
      },
    ],
    steps: [
      {
        id: 1,
        title: "Transformer Attention",
        duration: "10:20",
        type: "video",
        description: "Learn how self-attention powers modern LLMs.",
      },
      {
        id: 2,
        title: "Weight Optimization",
        duration: "Sandbox",
        type: "lab",
        description: "Interact with a visual model optimization simulator.",
      },
      {
        id: 3,
        title: "Fine-Tuning Protocol",
        duration: "14:00",
        type: "project",
        description: "Apply your learning to a mini tuning workflow.",
      },
    ],
    resources: [
      { title: "Attention Cheatsheet", type: "PDF" },
      { title: "Prompt Evaluation Template", type: "Template" },
      { title: "Mini Fine-Tune Starter Repo", type: "Repo" },
    ],
  },

  {
    id: "bitcoin-economics",
    slug: "bitcoin-economics",
    title: "Bitcoin Protocol Deep Dive",
    category: "crypto",
    level: "Expert",
    students: "840",
    status: "Live Now",
    description:
      "Analyze the Bitcoin protocol, UTXO design, and on-chain market behavior.",
    longDescription:
      "This course explains Bitcoin as both a technical protocol and an economic system. You’ll explore transaction structure, mempool behavior, market cycles, and practical chain analysis.",
    instructor: "Prof. Kevin Otieno",
    duration: "6 weeks",
    progress: 28,
    xpReward: 500,
    rating: 4.8,
    gradient: "from-orange-600/20 to-amber-600/20",
    border: "border-orange-500/30",
    color: "text-orange-400",
    icon: <Coins size={18} />,
    toolIcon: <LineChart size={16} className="text-orange-400" />,
    tools: ["Live Ticker", "Mempool Sim", "Cycle Analyzer"],
    outcomes: [
      "Understand Bitcoin transaction flow",
      "Interpret on-chain and market behavior",
      "Read macro crypto trends with confidence",
    ],
    modules: [
      {
        id: "m1",
        title: "Protocol Mechanics",
        summary: "UTXO model, block structure, miners and nodes.",
        duration: "1h 30m",
        lessons: 6,
      },
      {
        id: "m2",
        title: "Mempool & Market Dynamics",
        summary: "Fees, congestion, order flow, and liquidity.",
        duration: "1h 50m",
        lessons: 8,
      },
      {
        id: "m3",
        title: "Bitcoin Cycles",
        summary: "Halvings, narratives, and macro behavior.",
        duration: "1h 20m",
        lessons: 5,
      },
    ],
    steps: [
      {
        id: 1,
        title: "UTXO Model Overview",
        duration: "5:20",
        type: "video",
        description: "Understand how Bitcoin transactions are structured.",
      },
      {
        id: 2,
        title: "Live Mempool Analysis",
        duration: "Interactive",
        type: "lab",
        description: "Explore congestion and fee pressure visually.",
      },
      {
        id: 3,
        title: "Halving Cycle Theory",
        duration: "12:00",
        type: "project",
        description: "Study the macro cycle behavior of Bitcoin.",
      },
    ],
    resources: [
      { title: "UTXO Visual Guide", type: "Guide" },
      { title: "Mempool Reading Notes", type: "PDF" },
      { title: "Cycle Tracking Spreadsheet", type: "Template" },
    ],
  },

  {
    id: "copywriting-framework",
    slug: "copywriting-framework",
    title: "High-Ticket Closing Lab",
    category: "sales",
    level: "Intermediate",
    students: "3.5k",
    status: "Operational",
    description:
      "Master persuasive communication, objections, and premium offer closing.",
    longDescription:
      "This course teaches high-converting sales psychology, objection handling, offer positioning, and practical voice-based roleplay for real client conversations.",
    instructor: "Coach Sarah Njeri",
    duration: "5 weeks",
    progress: 45,
    xpReward: 500,
    rating: 4.7,
    gradient: "from-pink-600/20 to-rose-600/20",
    border: "border-pink-500/30",
    color: "text-pink-400",
    icon: <PenTool size={18} />,
    toolIcon: <Mic2 size={16} className="text-pink-400" />,
    tools: ["Voice AI Bot", "Objection Map", "Offer Script Builder"],
    outcomes: [
      "Handle objections with authority",
      "Build premium offer confidence",
      "Improve persuasive communication",
    ],
    modules: [
      {
        id: "m1",
        title: "Sales Psychology",
        summary: "Decision triggers, framing, and authority.",
        duration: "1h 18m",
        lessons: 6,
      },
      {
        id: "m2",
        title: "Objection Handling",
        summary: "Price, trust, urgency, and clarity barriers.",
        duration: "1h 42m",
        lessons: 8,
      },
      {
        id: "m3",
        title: "Closing Systems",
        summary: "Structure calls that convert consistently.",
        duration: "1h 35m",
        lessons: 7,
      },
    ],
    steps: [
      {
        id: 1,
        title: "Frame Control Basics",
        duration: "4:15",
        type: "video",
        description: "Learn how to hold authority in a conversation.",
      },
      {
        id: 2,
        title: "Voice AI Roleplay",
        duration: "Active",
        type: "lab",
        description: "Practice live objection handling in the lab.",
      },
      {
        id: 3,
        title: "Closing The Whale",
        duration: "08:00",
        type: "project",
        description: "Simulate a premium sales conversation.",
      },
    ],
    resources: [
      { title: "Closing Script Template", type: "Template" },
      { title: "Objection Handling PDF", type: "PDF" },
      { title: "Authority Phrases Cheatsheet", type: "Cheatsheet" },
    ],
  },

  {
    id: "fullstack-systems",
    slug: "fullstack-systems",
    title: "Fullstack System Architecture",
    category: "dev",
    level: "Advanced",
    students: "2.1k",
    status: "Maintenance",
    description:
      "Learn to design and scale modern fullstack systems from backend to frontend.",
    longDescription:
      "This course teaches how to think like a software architect: designing services, structuring applications, improving reliability, and building scalable fullstack systems.",
    instructor: "Eng. Daniel Kiptoo",
    duration: "9 weeks",
    progress: 72,
    xpReward: 500,
    rating: 4.9,
    gradient: "from-emerald-600/20 to-teal-600/20",
    border: "border-emerald-500/30",
    color: "text-emerald-400",
    icon: <Code2 size={18} />,
    toolIcon: <Terminal size={16} className="text-emerald-400" />,
    tools: ["IDE Terminal", "Load Tester", "Architecture Canvas"],
    outcomes: [
      "Design scalable backend systems",
      "Understand architecture tradeoffs",
      "Ship production-ready applications",
    ],
    modules: [
      {
        id: "m1",
        title: "System Design Foundations",
        summary: "Architecture principles, APIs, state, and reliability.",
        duration: "2h 05m",
        lessons: 9,
      },
      {
        id: "m2",
        title: "Scaling Fullstack Apps",
        summary: "Caching, queues, observability, and resilience.",
        duration: "2h 15m",
        lessons: 10,
      },
      {
        id: "m3",
        title: "Production Thinking",
        summary: "Deployments, stress tests, and failure handling.",
        duration: "1h 48m",
        lessons: 7,
      },
    ],
    steps: [
      {
        id: 1,
        title: "Architecture Briefing",
        duration: "6:30",
        type: "video",
        description: "Get introduced to system design principles.",
      },
      {
        id: 2,
        title: "Node Implementation",
        duration: "Interactive",
        type: "lab",
        description: "Use a simulated engineering environment.",
      },
      {
        id: 3,
        title: "System Stress Test",
        duration: "15:00",
        type: "project",
        description: "Run and analyze production-style load behavior.",
      },
    ],
    resources: [
      { title: "System Design Notes", type: "PDF" },
      { title: "Architecture Starter Repo", type: "Repo" },
      { title: "Backend Reliability Checklist", type: "Guide" },
    ],
  },
];

export const getCourseById = (id: string) =>
  PLATFORM_COURSES.find((course) => course.id === id);

export const getFeaturedCourses = () => PLATFORM_COURSES.slice(0, 4);